#!/usr/bin/bash

# move kitty config to ~/linux-dotfiles

echo "Select Option:

1: Kitty
2: Fish
3: Termite
4: Astrovim 
5: i3
6: neofetch
7: zathura
8: picom
9: latex
10: alacritty
11: Only push dotfiles
12: Copy all configs

"
read OPTION


if [ "$OPTION" = "1"  ];
then
	sudo cp -R ~/.config/kitty/ ~/linux-dotfiles && echo "Copied Kitty Directory to ~/linux-dotfiles" || echo "failed to move configs to linux-dotfiles"

elif [ "$OPTION" = "2" ];
then
	sudo cp ~/.config/fish/config.fish ~/linux-dotfiles/fish && echo "Copied Fish Config to ~/linux-dotfiles/fish" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "3" ];
then
	sudo cp ~/.config/termite/config ~/linux-dotfiles/termite\ configs && echo "copied termite config to ~/linux-dotfiles/termite" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "4" ];
then
	sudo cp ~/.config/nvim/init.lua ~/linux-dotfiles/astrovim/ && echo "Copied neovim config (init.lua) to ~/linux-dotfiles/astrovim " || echo "falied to move config (init.lua) to linux-dotfiles"
	sudo cp ~/.config/nvim/lua/core/mappings.lua ~/linux-dotfiles/astrovim/ && echo "Copied neovim config (mappings.lua) to ~/linux-dotfiles/astrovim " || echo "falied to move config (mappings.lua) to linux-dotfiles"
	sudo cp ~/.config/nvim/lua/core/plugins.lua ~/linux-dotfiles/astrovim/ && echo "Copied neovim config (plugins.lua) to ~/linux-dotfiles/astrovim " || echo "falied to move config (plugins.lua) to linux-dotfiles"
	sudo cp ~/.config/nvim/lua/core/options.lua ~/linux-dotfiles/astrovim/ && echo "Copied neovim config (options.lua) to ~/linux-dotfiles/astrovim " || echo "falied to move config (options.lua) to linux-dotfiles"

elif [ "$OPTION" = "5" ];
then
	sudo cp -R ~/.config/i3/* ~/linux-dotfiles/i3 && echo "Move i3 configs to ~/linux-dotfiles/i3" || echo "Failed to move i3 configs to ~/linux-dotfiles/i3" 
elif [ "$OPTION" = "6" ];
then
	sudo cp ~/.config/neofetch/config.conf ~/linux-dotfiles/neofetch && echo "Copied neofetch config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "7" ];
then
	sudo cp ~/.config/zathura/zathurarc ~/linux-dotfiles/zathura && echo "Copied zathura config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "8" ];
then
	sudo cp ~/.config/picom/picom.conf ~/linux-dotfiles/picom && echo "Copied picom config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "9" ];
then
	sudo cp ~/.config/nvim/UltiSnips/tex.snippets ~/linux-dotfiles/latex && echo "Copied latex config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "10" ];
then
	sudo cp ~/.config/alacritty/alacritty.yml ~/linux-dotfiles/alacritty && echo "Copied alacritty config to ~/linux-dotfiles/alacritty" || echo "failed to move config to linux-dotfiles"

elif [ "$OPTION" = "11" ];
then
	sudo git -C ~/linux-dotfiles add . && sudo git -C ~/linux-dotfiles commit -m "changes" && git -C ~/linux-dotfiles push && echo "Pushed changes to github repository Successfully" || echo "Failed to Push changes to github repository"

elif [ "$OPTION" = "12" ];
then
	sudo cp -R ~/.config/fish/ ~/linux-dotfiles/.config/ && echo "Copied Fish Config to ~/linux-dotfiles/fish" || echo "failed to move config to linux-dotfiles";
	sudo cp -R ~/.config/kitty/ ~/linux-dotfiles/.config/ && echo "Copied Kitty Directory to ~/linux-dotfiles/kitty" || echo "failed to move Directory to linux-dotfiles";
	sudo cp ~/.config/termite/config ~/linux-dotfiles/.config/termite\ configs && echo "copied termite config to ~/linux-dotfiles/termite" || echo "failed to move config to linux-dotfiles";
	sudo cp -R ~/.config/nvim ~/linux-dotfiles/.config/ && echo "copied nvim Directory to linux-dotfiles" || echo "copied nvim Directory to linux-dotfiles"
	sudo cp -R ~/.config/i3 ~/linux-dotfiles/.config/ && echo "copied i3 Directory to linux-dotfiles" || echo "copied i3 Directory to linux-dotfiles"
	sudo cp ~/.config/neofetch/config.conf ~/linux-dotfiles/.config/neofetch && echo "Copied neofetch config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
	sudo cp ~/.config/zathura/zathurarc ~/linux-dotfiles/.config/zathura && echo "Copied zathura config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
	sudo cp -R ~/.config/picom ~/linux-dotfiles/.config/ && echo "Copied picom config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
	sudo cp ~/.config/alacritty/alacritty.yml ~/linux-dotfiles/.config/alacritty && echo "Copied alacritty config to ~/linux-dotfiles/alacritty" || echo "failed to move config to linux-dotfiles";
	sudo cp -R ~/backgrounds ~/linux-dotfiles && echo "Moved Backgrounds Directory To ~/linux-dotfiles/Backgrounds" || echo "Failed to move Backgrounds Directory To ~/linux-dotfiles/Backgrounds"
	sudo cp /usr/bin/moveConfigs ~/linux-dotfiles/bashscripts/configMover && echo "Moved config mover to ~/linux-dotfiles/configMover" || echo "failed to move configmove to ~/linux-dotfiles/configMover"
	sudo cp /usr/bin/pall ~/linux-dotfiles/bashscripts/ && echo "Moved push-all tool to ~/linux-dotfiles/pall" || echo "Failed to move push-all tool to ~/linux-dotfiles/pall"
	sudo cp /usr/bin/i3changer ~/linux-dotfiles/bashscripts/i3ConfigChanger && echo "Moved i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger" || echo "Failed to move i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger "
	sudo cp -R ~/.config/rofi ~/linux-dotfiles/.config/ && echo "moved rofi configs to linux-dotfiles" || echo "Failed to move rofi configs to linux dotfiles"
	sudo cp -R ~/.config/rofibackups ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/qutebrowser ~/linux-dotfiles/.config/ && echo "moved qutebrowser configs to linux-dotfiles" || echo "failed to move qutebrowser configs to linux-dotfiles"
	sudo cp ~/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.10/site-packages/pycodestyle.py ~/linux-dotfiles/pycodestyle && echo "moved pycodestyle to linex-dotfiles" || echo "failed to move pycodestyle to linux-dotfiles"
	sudo cp ~/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.10/site-packages/pyflakes/messages.py ~/linux-dotfiles/pyflakes && echo "moved pyflakes messages.py to linux-dotfiles" || echo "failed to move pyflakes messages.py to linux-dotfiles"
	sudo cp -R ~/.config/tint2 ~/linux-dotfiles/.config/ && echo "Moved tint2 Directory to linux-dotfiles" || echo "Failed to move configs to linux-dotfiles"
	sudo cp -R ~/.config/polybar ~/linux-dotfiles/.config/ && echo "Copied polybar Directory to linux-dotfiles" || echo "Copied polybar Directory to linux-dotfiles"
	sudo cp -R ~/.config/inkscape-figures ~/linux-dotfiles/.config
	sudo cp -R ~/Pictures/Grids ~/linux-dotfiles/Pictures
	sudo cp -R ~/Pictures/Graphs ~/linux-dotfiles/Pictures
	sudo cp -R ~/dev/latex/template/preamble.tex ~/linux-dotfiles/latex
	sudo cp -R ~/dev/latex/template/macros.tex ~/linux-dotfiles/latex
	sudo cp ~/.tmux.conf ~/linux-dotfiles/.config/tmux
	sudo cp -R ~/.config/hypr ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/HyprV ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/waybar ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/cava ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/wofi ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/eww ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/spotify ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/spicetify ~/linux-dotfiles/.config/
	sudo cp -R ~/.config/vis ~/linux-dotfiles/.config/

else
	echo "Invalid Option"
fi

echo "Pushing changes to github repository"

sudo git -C ~/linux-dotfiles add . && sudo git -C ~/linux-dotfiles commit -m "changes" && git -C ~/linux-dotfiles push && echo "Pushed changes to github repository Successfully" || echo "Failed to Push changes to github repository"

