#!/usr/bin/bash

# Push all github repositories

# Linux-dotfiles, Linux Resources, programming resources, dev

sudo git -C ~/linux-dotfiles add . && sudo git -C ~/linux-dotfiles commit -m "commit" && git -C ~/linux-dotfiles push && echo "Successfully pushed changes to directory linux-dotfiles" || echo "Failed to push changes to directory linux-dotfiles or everything is up to date"

sudo git -C ~/Linux-Resources add . && sudo git -C ~/Linux-Resources commit -m "commit" && git -C ~/Linux-Resources && echo "Successfully pushed changes to directory Linux Resources " || echo "Failed to push changes to directory Linux Resources or everything is up to date"

sudo git -C ~/springsemester add . && sudo git -C ~/springsemester commit -m "commit" && git -C ~/springsemester push && echo "Successfully pushed changes to directory dev" || echo "Failed to push changes to directory dev or everything is up to date"

sudo git -C ~/dev add . && sudo git -C ~/dev commit -m "commit" && git -C ~/dev push && echo "Successfully pushed changes to directory dev" || echo "Failed to push changes to directory dev or everything is up to date"

sudo git -C ~/earn add . && sudo git -C ~/earn commit -m "commit" && git -C ~/earn push && echo "Successfully pushed changes to directory earn" || echo "Failed to push changes to directory earn or everything is up to date"

sudo git -C ~/learn add . && sudo git -C ~/learn commit -m "commit" && git -C ~/learn push && echo "Successfully pushed changes to directory dev" || echo "Failed to push changes to directory dev or everything is up to date"

