#!/usr/bin/bash
main() { (( ${#} < 1 )) && echo "Usage <file ext> ..." && exit 1;
        
    EXP=()
    for EXT in "$@"; do
        EXP+=( -name "*.${EXT}" -o )
    done

    unset 'EXP[-1]'

    find . -type f \( "${EXP[@]}" \) -print0 | xargs -0 -r nvim

}; main "$@"
