#!/usr/bin/bash
main() { [[ ${#} < 1 ]] && echo "Usage <file ext> ..." && exit 1; }
    LINE="find . -type f -name *.${1}";
    for arg in $(seq 2 $((${#}))); do
        LINE+=" -o -name *.${!arg}" 
    done; $LINE | xargs nvim
}; main "$@"
