#!/usr/bin/bash

function halt { echo "Usage: ./pdftex file"; exit 1; }

function main {
    [[ $# != 1 ]] && halt

    inkscape --export-type=pdf --export-latex --export-area-page $1.svg
} 
main "${@}"
