#!/usr/bin/bash

main()
{
    DUNDEF_PATH=$HOME/dev/roadmap/python/dunder/definitions/main.tex
    DUNEX_PATH=$HOME/dev/roadmap/python/dunder/examples/main.tex
    TMP_PATH=$HOME/tmp/python

    # Open Dunder Definitions Latex File
    nohup kitty -- > /dev/null nvim $DUNDEF_PATH 2>&1 &

    # Open Dunder Examples Latex File
    nohup kitty -- > /dev/null nvim $DUNEX_PATH 2>&1 &

    # Open Terminal in $HOME/tmp/python
    nohup kitty -- > /dev/null cd $TMP_PATH 2>&1 &

}
main
