#!/bin/bash

# Define your directories
declare -a dirs=(
    "$HOME/niu"
    "$HOME/niu/math/discrete/notes"
    "$HOME/niu/math/calc/calc2/lecturenotes"
    "$HOME/niu/math/calc/calc2/psets"
    "$HOME/niu/math/discrete/notes"
    "$HOME/niu/math/allmath1"
    "$HOME/niu/math/allmath2"
    "$HOME/niu/cs/cs240/notes/lectures/full"
    "$HOME/niu/cs/cs240/psets/"
    "$HOME/tmp"
    "$HOME/dev"
    "$HOME/niu/cs/cs240/notes/lectures/full" 
    "$HOME/niu/cs/cs240/notes/booknotes/notes"
# ... add more paths as needed
)

# Use Rofi to get a directory selection
chosen_dir=$(printf '%s\n' "${dirs[@]}" | rofi -dmenu -theme /home/datura/.config/rofi/launchers/type-3/style-3.rasi -p "Where are you going?")

# Check if chosen directory is not empty and exists
if [ -n "$chosen_dir" ] && [ -d "$chosen_dir" ]; then
    echo "$chosen_dir"
else
    echo ""
fi

